language: c

compiler:
  - gcc
  - clang

dist: xenial

addons:
  apt:
    packages:
     - libpcre2-dev

# Settings to try
env:
 - OPTIONS="-DCMAKE_BUILD_TYPE=Release -DBUILD_STATICALLY_LINKED_EXE=ON -DPCRE=ON"
 - OPTIONS="-DCMAKE_BUILD_TYPE=Release -DBUILD_STATICALLY_LINKED_EXE=OFF -DPCRE=ON"
 - OPTIONS="-DCMAKE_BUILD_TYPE=Release -DBUILD_STATICALLY_LINKED_EXE=ON -DPCRE=OFF"
 - OPTIONS="-DCMAKE_BUILD_TYPE=Release -DBUILD_STATICALLY_LINKED_EXE=OFF -DPCRE=OFF"

# Run the Build script
script:
 - mkdir _build
 - cd _build
 - cmake .. -DCMAKE_INSTALL_PREFIX=../_install $OPTIONS
 - cmake --build . --target install

# Run Tests
after_script:
 - ctest -VV --output-on-failure .

# Notify the mailing list
notifications:
 email:
   on_success: change
   on_failure: always
