image:
  - Visual Studio 2017
  
environment:
  CMAKE_GENERATOR: 'Visual Studio 15 2017 Win64'
  CONFIG: Release
  ARCH: x64
  CMAKE_INSTALL_PREFIX: ..\build
  PCRE_DEST: C:\projects\bin\%ARCH%-static\pcre
  CORE_DEST: C:\projects\bin\%ARCH%-static\core
  
install:
  - cmake --version
  - git submodule init
  - git submodule update
  - cd C:\projects
  # Download PCRE sources
  - curl -o pcre.zip https://ftp.pcre.org/pub/pcre/pcre-8.41.zip
  - 7z x -y pcre.zip > nul
  - rename pcre-8.41 pcre
  # Build and install PCRE
  - mkdir %PCRE_DEST%
  - cd %PCRE_DEST%
  - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX="%CMAKE_INSTALL_PREFIX%" -DPCRE_STATIC_RUNTIME="ON" -DBUILD_SHARED_LIBS="OFF" -DPCRE_BUILD_PCRECPP=OFF -DPCRE_BUILD_PCREGREP=OFF -DPCRE_BUILD_TESTS=OFF C:\projects\pcre
  - cd %PCRE_DEST%
  - cmake --build %PCRE_DEST% --target install -- /p:Configuration=%CONFIG%
  
build_script:
  # Build and install editorconfig-core-c
  - mkdir %CORE_DEST%
  - cd %CORE_DEST%
  - cmake -G "%CMAKE_GENERATOR%" -DCMAKE_INSTALL_PREFIX="%CMAKE_INSTALL_PREFIX%" -DMSVC_MD="OFF" -DPCRE_STATIC="ON" C:\projects\editorconfig-core-c
  - cmake --build %CORE_DEST% --target install -- /p:Configuration=%CONFIG%

test_script:
  # Run the core tests
  - cd %CORE_DEST%
  - cmake --build %CORE_DEST% --target run_tests -- /p:Configuration=%CONFIG%

on_failure:
  - echo. && echo. && echo. && echo "Tests for editorconfig-core-c failed. Here is their detailed output:" && echo. && echo. && echo.
  - type C:\projects\bin\x64-static\core\Testing\Temporary\LastTest.log
